"""Functional tests for immutable Teacher fixture provenance."""

from datetime import timedelta
from pathlib import Path

import pytest

from capability_capsule.eval.fixture_provenance import (
    inspect_fixture,
    verify_task_fixture,
)
from capability_capsule.eval.records import DatasetSplit
from capability_capsule.eval.tasks import TaskCategory, TaskDifficulty, TaskSpec


def write_fixture(root: Path, *, reverse_order: bool = False) -> None:
    files: tuple[tuple[str, bytes], ...] = (
        ("src/example.py", b"VALUE = 1\n"),
        ("README.md", b"# Example fixture\n"),
    )
    if reverse_order:
        files = tuple(reversed(files))

    for relative_path, content in files:
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)


def make_task(revision: str) -> TaskSpec:
    return TaskSpec(
        task_id="task-001",
        fixture_id="fixture-001",
        fixture_family_id="fixture-family-001",
        fixture_revision=revision,
        defect_family="constant-location",
        split=DatasetSplit.TRAIN,
        category=TaskCategory.CODE_SEARCH,
        difficulty=TaskDifficulty.EASY,
        task="Find the VALUE constant.",
        knowledge_distance=0.1,
        logical_arrival=timedelta(0),
        time_limit=timedelta(minutes=2),
        allowed_tools=("exec_command",),
        validation_ids=("exact-path:value-constant",),
    )


def test_inspect_fixture_is_stable_across_roots_and_creation_order(
    tmp_path: Path,
) -> None:
    first_root = tmp_path / "first"
    second_root = tmp_path / "second"
    write_fixture(first_root)
    write_fixture(second_root, reverse_order=True)

    first = inspect_fixture("fixture-001", first_root)
    second = inspect_fixture("fixture-001", second_root)

    assert first.revision == second.revision
    assert first.file_count == 2
    assert first.byte_count == len(b"VALUE = 1\n# Example fixture\n")
    assert len(first.revision) == 64


def test_inspect_fixture_detects_content_and_path_changes(tmp_path: Path) -> None:
    root = tmp_path / "fixture"
    write_fixture(root)
    original = inspect_fixture("fixture-001", root)

    (root / "src/example.py").write_bytes(b"VALUE = 2\n")
    changed_content = inspect_fixture("fixture-001", root)
    assert changed_content.revision != original.revision

    (root / "src/example.py").rename(root / "src/renamed.py")
    changed_path = inspect_fixture("fixture-001", root)
    assert changed_path.revision != changed_content.revision


def test_inspect_fixture_ignores_known_runtime_cache_artifacts(
    tmp_path: Path,
) -> None:
    root = tmp_path / "fixture"
    write_fixture(root)
    original = inspect_fixture("fixture-001", root)
    bytecode = root / "src" / "__pycache__" / "example.cpython-313.pyc"
    pytest_cache = root / ".pytest_cache" / "v" / "cache" / "nodeids"
    bytecode.parent.mkdir(parents=True)
    pytest_cache.parent.mkdir(parents=True)
    bytecode.write_bytes(b"generated bytecode")
    pytest_cache.write_text("generated test cache", encoding="utf-8")

    inspected = inspect_fixture("fixture-001", root)

    assert inspected == original


def test_inspect_fixture_rejects_empty_fixture(tmp_path: Path) -> None:
    root = tmp_path / "empty"
    root.mkdir()

    with pytest.raises(ValueError, match="must contain at least one file"):
        inspect_fixture("fixture-empty", root)


def test_inspect_fixture_rejects_missing_directory(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="does not exist"):
        inspect_fixture("fixture-missing", tmp_path / "missing")


def test_inspect_fixture_rejects_symbolic_links(tmp_path: Path) -> None:
    root = tmp_path / "fixture"
    write_fixture(root)
    link = root / "linked.py"

    try:
        link.symlink_to(root / "src/example.py")
    except OSError:
        pytest.skip("Symbolic links are unavailable on this platform")

    with pytest.raises(ValueError, match=r"symbolic link.*linked\.py"):
        inspect_fixture("fixture-001", root)


def test_verify_task_fixture_accepts_exact_revision(tmp_path: Path) -> None:
    root = tmp_path / "fixture"
    write_fixture(root)
    snapshot = inspect_fixture("fixture-001", root)
    task = make_task(snapshot.revision)

    assert verify_task_fixture(task, root) == snapshot


def test_verify_task_fixture_rejects_changed_fixture(tmp_path: Path) -> None:
    root = tmp_path / "fixture"
    write_fixture(root)
    task = make_task(inspect_fixture("fixture-001", root).revision)
    (root / "src/example.py").write_bytes(b"VALUE = 9\n")

    with pytest.raises(ValueError, match=r"revision mismatch.*task-001"):
        verify_task_fixture(task, root)
